[package]
name = "rustploy-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
tokio.workspace = true
uuid.workspace = true
